C_OBJS=
ASM_OBJS=
COMPONENT=memcached-nf.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lclick -lcobj_format -lcos_kernel_api $(POSIX_HYPERCALL_LIB) -lcos_defkernel_api -lstdc++ -lsupc++

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib_NF.o
